### ISSUE TITLE
Not properly working, when data bus not multiple of 2

### ISSUE THREAD

**Issue by iwaniwaniwan012** [QianfengClarkShen/Tbps_CRC#3] opened 2023-10-08 16:05 UTC
Hello
Tried to use your parameterized ip core(byte enable version), it excellent work with bus when it multiple of 2. For example 256 bits. But when i tried to use it with 320 bits, it not generate proper CRC32 for Ethernet. 
Any help will be helpful

**Comment by QianfengClarkShen** [comment] 2023-10-08 18:21
Hi,

Thanks for pointing out the issue. I have committed a bug fix just now regarding this issue. I believe the issue is fixed now. Please pull the latest change and let me know if it works on your side.

If you do like this repo, I would like to ask you kindly star it.

Thanks,
Clark

**Closed** 2023-10-08 18:21 UTC
Labels: bug

**Comment by iwaniwaniwan012** [comment] 2023-10-10 18:39
> Hi,
> 
> Thanks for pointing out the issue. I have committed a bug fix just now regarding this issue. I believe the issue is fixed now with commit [25a6ced](https://github.com/QianfengClarkShen/Tbps_CRC/commit/25a6cedcf43c0768c0f5dd02bba326b569055774). Please pull the latest change and let me know if it works on your side.
> 
> If you do like this repo, I would like to ask you kindly star it.
> 
> Thanks, Clark

Thanks. This project is very good work!
I have tested new version and it works good with my parameters!
